[package]
name = "markdown-composer"
version = "0.2.0"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."

[dependencies]
aurelius = "0.2"
clap = "2"
log = "0.3.1"
log4rs = "0.6"
rmp-serde = "0.12"
rmpv = { version = "0.3", features = ["with-serde"] }
serde = "0.9"
serde_derive = "0.9"
