[package]
name = "markdown-composer"
version = "0.2.0"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."

[dependencies]
aurelius = "0.1.13"
clap = "2"
log = "0.3.1"
log4rs = { version = "0.4.8", features = [ "yaml" ] }
rmp = "0.7"
rmp-serde = "0.10"
serde = "0.8"
