[package]
name = "markdown-composer"
version = "0.2.1"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."

[dependencies]
aurelius = "0.2"
clap = "2"
log = "0.3.1"
log4rs = "0.6"
log-panics = "1"
serde = "0.9"
serde_derive = "0.9"

serde_json = { version = "0.9", optional = true }
rmp-serde = { version = "0.12", optional = true }

[features]
default = ["msgpack"]
msgpack = ["rmp-serde"]
json-rpc = ["serde_json"]
