refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "error.log"
    encoder:
      pattern: "%d [%t] %l %M:%m"

root:
  level: warn
  appenders:
    - file
